package com.arcsoft.arcfacedemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.arcsoft.arcfacedemo.db.dao.RegisterInfo;

import com.arcsoft.arcfacedemo.db.RegisterInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig registerInfoDaoConfig;

    private final RegisterInfoDao registerInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        registerInfoDaoConfig = daoConfigMap.get(RegisterInfoDao.class).clone();
        registerInfoDaoConfig.initIdentityScope(type);

        registerInfoDao = new RegisterInfoDao(registerInfoDaoConfig, this);

        registerDao(RegisterInfo.class, registerInfoDao);
    }
    
    public void clear() {
        registerInfoDaoConfig.clearIdentityScope();
    }

    public RegisterInfoDao getRegisterInfoDao() {
        return registerInfoDao;
    }

}
